@LocalApiRoot = http://localhost/Rest_Api/public/index.php
@RemoteApiRoot = http://159.89.23.142

# Register user
POST {{LocalApiRoot}}/user/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}

###

POST {{LocalApiRoot}}/todo/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty",
    "name": "important",
    "text": "very important"
}

###

GET  {{LocalApiRoot}}/todo/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}

###

PUT  {{LocalApiRoot}}/todo/1
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty",
    "name": "updated important",
    "text": "updated very important"
}

###

DELETE  {{LocalApiRoot}}/todo/5
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}