@LocalApiRoot = http://localhost/Rest_Api/public/index.php
@RemoteApiRoot = http://159.89.23.142


# Register user
POST {{RemoteApiRoot}}/user/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}

###

POST {{RemoteApiRoot}}/todo/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty",
    "name": "important",
    "text": "very important"
}

###


GET  {{RemoteApiRoot}}/todo/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}

###



PUT  {{RemoteApiRoot}}/todo/1
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty",
    "name": "updated important",
    "text": "updated very important"
}

###

DELETE  {{RemoteApiRoot}}/todo/1
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}

###

GET  {{RemoteApiRoot}}/files/
Client-Login: qwerty
Client-Password: qwerty

{
}

###

GET  {{RemoteApiRoot}}/files/upload.txt
Client-Login: qwerty
Client-Password: qwerty

{
}

###

DELETE  {{RemoteApiRoot}}/files/upload.txt
Client-Login: qwerty
Client-Password: qwerty

{
}

###
