@LocalApiRoot = http://localhost/Rest_Api/public/index.php

# Register user
POST {{LocalApiRoot}}/user/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty"
}

###

POST {{LocalApiRoot}}/todo/
Content-Type: application/json

{
    "login": "qwerty",
    "password": "qwerty",
    "name": "important",
    "text": "very important"
}